# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2026 Raúl Vílchez Ruiz <raulmicrosistemas@gmail.com>
#
# Makefile - Build instructions for hwbus-io
#



obj-m += hello.o

# obj-m += mi_modulo.o
# mi_modulo-y := hello.c otro.c otro_mas.c